# Generated by Django 3.0.8 on 2021-02-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApp', '0002_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='relation',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
