# Generated by Django 3.0.8 on 2021-02-18 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApp', '0003_auto_20210217_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='address',
        ),
        migrations.RemoveField(
            model_name='members',
            name='age',
        ),
        migrations.RemoveField(
            model_name='members',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
        migrations.AddField(
            model_name='members',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
