# Generated by Django 3.0.8 on 2021-02-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApp', '0004_auto_20210218_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileApp.UserInfo'),
        ),
    ]
