# Generated by Django 3.0.8 on 2021-02-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApp', '0005_auto_20210218_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
